AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template
Resources:
  MyEC2Instance: #ec2-instance template
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-02d1e544b84bf7502" #Another comment -- This is a Linux AMI
      InstanceType: t2.micro
      KeyName: formation

Type: AWS::EC2::SecurityGroupIngress
Properties: 
  CidrIp: 0.0.0.0/0
  FromPort: 22
  GroupName: cloudformationsg
  IpProtocol: TCP
  ToPort: 22


  

      

   