- name: register variable 
  hosts: all
  tasks:
    - name: get uptime
      shell:
          cmd: uptime
      register: UT

    - name: print uptime
      debug:
          msg: "this is Up time {{UT}}"  