- name: variables playbook
  hosts: all
  vars_files:
    - ./var.data
   
  tasks:
   - name: " print hello world1 "
     debug:
        msg: " Please visit {{ URL }} "

   - name: " print hello world2 "
     debug:
        msg: " Please visit {{ URL }} "
     vars:
         URL: "local.google.com"
   - name: "print url"
     debug:
         msg: "{{ URL }}"