- name: condition exaple
  hosts: all
  tasks:
   - name: redhat
     debug:
       msg: "this is Redhat family"
     when: ansible_distribution_file_variety == " RedHat "
   - name: ubuntu
     debug:
       msg: "this is Ubuntu"
     when: ansible_distribution_file_variety == " Ubuntu "