- name: condition exaple
  hosts: all
  tasks:
   - name: Centos
     debug:
       msg: "this is Centos"
     when: ansible_distribution_file_variety == " Centos "
   - name: ubuntu
     debug:
       msg: "this is Ubuntu"
     when: ansible_distribution_file_variety == " Ubuntu "