- name: condition exaple
  hosts: all
  tasks:
   - name: RedHat
     debug:
       msg: "this is RedHat family"
     when: ansible_distribution_file_variety == "RedHat" and ansible_distribution == "Centos"
   - name: ubuntu
     debug:
       msg: "this is Ubuntu"
     when: ansible_distribution_file_variety == " Ubuntu "