- name: variables playbook
  hosts: all
  vars:
  - URL: "global.google.com" 
  tasks:
   - name : print url
     debug:
      msg: "{{ URL }}"

   - name : print url2
     debug:
      msg: "{{ URL }}"
   - vars:
     URL: "local.google.com"

   - name: print url3
     debug:
      msg : "{{ URL }}"