- name: variables playbook
  hosts: all
  gather_facts: False
  vars:
    - URL1: "www.google.com"
    - URL2: "www.yahoo.com"
  tasks:
   - name: " print hello world1 "
     debug:
        msg: " Please visit {{ URL1 }} "

   - name: print os distribution
     debug:
      msg: "{{ ansible_distribution }}"
     ignore_errors: yes

   - name: print os distribution
     debug:
      msg: "{{ ansible_eth0.ipv4.address }}"
     ignore_errors: yes

   - name: " print hello world2 "
     debug:
          msg: " Please visit {{ URL }} "
     vars:
         URL : "local.google.com"

   - name: " print hello world3 "
     debug:
        msg: " Please visit {{ URL2 }} " 

   