- name: priveleges escalation demo
  hosts: all
  become : true
  tasks:
    - name: execute dmidecode cmd
      shell:
       args : /sbin/dmidecode
      register: OUTPUT
    - name: print output
      debug:
       msg :"{{ OUTPUT }}"




#for provide privilage for usr "become"is  provide  and is by default false make true"
#when we login in system ec2-user/centos that time you cant install package without sudo bcz this are local user.
#when we apply sudo we give to privilage to this local user