- name:
  hosts: all
  tasks:
    - name: execute dmidecode cmd
      shell:
      cmd : /sbin/dmidecode
      register: OUTPUT
    - name: print output
      debug:
       msg :"{{ OUTPUT }}"





#when we login in system ec2-user/centos that time you cant install package without sudo bcz this are local user.
#when we apply sudo we give to privilage to this local user