- name: register variable demo
  hosts: all
  tasks:
    - name: get uptime 
      shell:
         cmd: uptime
      register: UT

    - name: print up time
      debug: 
          msg: "the uptime is {{ UT }} "