- name: register variable demo
  hosts: all
  tasks:
    - name: get uptime 
      shell:
         cmd: uptime
      register: UT

    - name: print up time
      debug: 
          msg: "{{ UT.stdout }}"





 

# UT shows all details
 #cmd or args use for registered variable 
 #UT.stdout show only perticular output 
 #register variable is a way to capture from task execution and store it in a variable.