- name: tags demo
  hosts: all
  tasks:
    - name: print redhat
      debug:
       msg: "this is Redhat"
      tags:
         - Redhat
       
    - name: print Ubuntu
      debug:
       msg: "this is Ubuntu"
      tags:
       - Ubuntu

    - name: print kali linux
      debug:
       msg: "this is kali linux"
      tags:
      - kali linux


#tags is use for identity 
#IN case i want skip Ubuntu task that time this var is use"ansible-playbook tags.yaml --skip-tags=Ubuntu"