- name: url split with the help of string
  hosts: all
  tasks:
    - name: url split
      debug:
        msg: "{{'https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.tar.gz' | urlsplit('path') }}"

    - name: url split basename
      debug:
        msg: "{{ 'https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.tar.gz' | urlsplit('path') | basename }}"

    - name: path filter
      debug:
        msg: "{{ 'https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.tar.gz' | basename }}"

    
    - name: regex replace tar.gz to only name
      debug:
      msg: "{{ 'apache-tomcat-8.5.78.tar.gz ' | regex_replace('.tar.gz','') }}"
    
    #way of split path of dir or extract file