- name: variables playbook
  hosts: all
  vars:
    - URL1: "www.google.com"
    - URL2: "www.yahoo.com"
  vars_prompt:
  - name: URL
    prompt: "Enter the URL of Company"
    unsafe: no
    private: yes
  tasks:
   - name: " print hello world1 "
     debug:
        msg: " Please visit {{ URL1 }} "

   - name: " print hello world2 "
     debug:
          msg: " Please visit {{ URL }} "
     vars:
         URL : "local.google.com"

   - name: " print hello world3 "
     debug:
        msg: " Please visit {{ URL2 }} "