- name: variables playbook
  hosts: all
  vars:
    - URL: "www.google.com"
  vars_prompt:
  - name: my_password_with_weird_chars
    prompt: "Enter the URL of Company"
    unsafe: no
    private: yes
  tasks:
   - name: " print hello world1 "
     debug:
        msg: " Please visit {{ URL }} "

   - name: " print hello world2 "
     debug:
          msg: " Please visit {{ URL }} "
     vars:
         URL : "local.google.com"

   - name: " print hello world3 "
     debug:
        msg: " Please visit {{ URL }} "