- name: web server playbook
  hosts: all
  become: true
  tasks:
   - name: install httpd package
     yum:
       name: httpd
       state: latest

   - name: start and enabled service
     service:
      name: httpd
      stage: started
      #enabled: yes

   - name: upload website in /var/www/html
     copy:
      src: ./index.html
      dest: /var/www/html
     
