- name: web server playbook
  hosts: all
  tasks:
   - name: install httpd package
     yum:
       name: httpd
       state: latest
   - name: start and enable service
     service:
      name: httpd
      stage: started
      enabled: yes
   - name: upload website in /var/www/html
     src: ./index.html
     dest: /var/www/html/
     remote src: yes
     