- name: url split example
  hosts: all
  tasks:
    - name: url split
      debug: 
          msg: "{{ 'https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.81/bin/apache-tomcat-8.5.81.tar.gz' | urlsplit ('path') }}"

    - name: url split
      debug: 
          msg: "{{ 'https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.81/bin/apache-tomcat-8.5.81.tar.gz' | urlsplit ('path') | basename }}"

    - name: url filter 
      debug: 
          msg: "{{ 'https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.81/bin/apache-tomcat-8.5.81.tar.gz' | basename }}"


    - name: regex replace tar.gz to only name
      debug:
       msg: "{{ 'apache-tomcat-8.5.78.tar.gz ' | regex_replace('.tar.gz','') }}"