Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: 't2.micro'
      SecurityGroups: 'sg-029011d94639a2680'
      KeyName: 'flame.pem'
      ImageId: 'ami-02d1e544b84bf7502'
      Region: us-east-2
 