- name: install java
  package:
     name: java
     state: latest

- name: download tomcat 8 
  get_url: 
      url: {{ URL }}
      dest: /opt

- name: unzip tomcat 
  unarchive:
      src: /opt/{{ ZIP_PATH }}
      dest: /opt/
      remote_src: yes

- name:  download student.war
  get_url:
      url: {{ APP_URL }}