- name: install java
  package:
     name: java
     state: latest

- name: download tomcat 8 
  get_url: 
      url: "{{ URL }}"
      dest: "/opt"
      validate_certs: no

- name: unzip tomcat 
  unarchive:
      src: "/opt/{{ URL_PATH }}"
      dest: "/opt/"
      remote_src: yes

- name:  download student.war
  get_url:
      url: "{{ APP_URL }}"
      src: "{{ TOMCAT_PATH }}/webapps"

- name: catalina service start and stop
  shell: '{{ TOMCAT_PATH }}/bin/catalina.sh start'
  



