- name: install java
  package:
     name: java
     state: latest

- name: download tomcat 8 
  get_url: 
      url: "{{ URL }}"
      dest: "/opt"
      validate_certs: no

- name: unzip tomcat 
  unarchive:
      src: "/opt/{{ URL_PATH }}"
      dest: "/opt/"
      remote_src: yes

- name:  download student.war
  get_url:
      url: "{{ APP_URL }}"
      dest: "{{ TOMCAT_PATH }}/webapps"

- name: upload configure file
  template:
      src: ./context.xml
      dest: /opt/{{ TOMCAT_PATH }}/conf/context.xml


- name: store my sql connector
  get_url:
      url: "{{ MYSQL_LIB_URL }}"
      dest: /opt/{{ TOMCAT_PATH }}/lib/



#- name: catalina service start and stop
#  shell: '{{ TOMCAT_PATH }}/bin/catalina.sh start'
  



